version: '3'
services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - '6500:5432'
    restart: always
    env_file:
      - ./.env
    volumes:
      - postgres-db:/var/lib/postgresql/data
  
  web_app:
    build: ./
    container_name: web_app
    ports:
      - 80:8000
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    env_file:
      - ./.env
    
volumes:
  postgres-db:

