"""empty message

Revision ID: 726014de5f47
Revises: 4c2ad5775e65
Create Date: 2025-04-06 18:19:17.136563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '726014de5f47'
down_revision: Union[str, None] = '4c2ad5775e65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('user_id', sa.UUID(), nullable=False))
    op.add_column('orders', sa.Column('instrument_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'orders', 'instruments', ['instrument_id'], ['id'])
    op.create_foreign_key(None, 'orders', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'instrument_id')
    op.drop_column('orders', 'user_id')
    # ### end Alembic commands ###
