"""DECIMAL -> FLOAT CHANGE

Revision ID: 895bb4f6ea2f
Revises: 25f846eaaa5a
Create Date: 2025-04-08 20:11:56.177994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '895bb4f6ea2f'
down_revision: Union[str, None] = '25f846eaaa5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('balance', 'amount',
               existing_type=sa.NUMERIC(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('orders', 'price',
               existing_type=sa.NUMERIC(),
               type_=sa.Float(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'price',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('balance', 'amount',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    # ### end Alembic commands ###
