"""deleted and filled changes

Revision ID: 152128bc1e56
Revises: 8ec6df3f3460
Create Date: 2025-05-07 16:38:28.098252

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "152128bc1e56"
down_revision: Union[str, None] = "8ec6df3f3460"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('orders', 'cancelled')
    # op.add_column('orders', sa.Column('filled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # op.drop_column('orders', 'filled')
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('orders', sa.Column('cancelled', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # op.drop_column('orders', 'cancelled')
    # ### end Alembic commands ###
