"""Couple fields change

Revision ID: 25f846eaaa5a
Revises: e7dd78bdc9b3
Create Date: 2025-04-08 19:56:03.539091

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "25f846eaaa5a"
down_revision: Union[str, None] = "e7dd78bdc9b3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("balance", sa.Column("amount", sa.DECIMAL(), nullable=False))
    op.drop_column("balance", "count")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "balance", sa.Column("count", sa.INTEGER(), autoincrement=False, nullable=False)
    )
    op.drop_column("balance", "amount")
    # ### end Alembic commands ###
