"""Soft delete integration

Revision ID: 2953d71ab83e
Revises: 895bb4f6ea2f
Create Date: 2025-04-11 14:13:09.906752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2953d71ab83e'
down_revision: Union[str, None] = '895bb4f6ea2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('instrument_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.UUID(), nullable=False),
    sa.Column('currency_amount', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['currency'], ['instruments.id'], ),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('instruments', sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True))
    op.drop_constraint('instruments_name_key', 'instruments', type_='unique')
    op.drop_constraint('instruments_ticker_key', 'instruments', type_='unique')
    op.drop_column('instruments', 'updated_at')
    op.drop_column('orders', 'updated_at')
    op.add_column('users', sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True))
    op.drop_column('users', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_column('users', 'deleted_at')
    op.add_column('orders', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('instruments', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.create_unique_constraint('instruments_ticker_key', 'instruments', ['ticker'])
    op.create_unique_constraint('instruments_name_key', 'instruments', ['name'])
    op.drop_column('instruments', 'deleted_at')
    op.drop_table('transactions')
    # ### end Alembic commands ###
