"""transaction base update

Revision ID: 5632e1aa97ba
Revises: 706e5fbfa926
Create Date: 2025-06-12 11:56:12.859944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5632e1aa97ba'
down_revision: Union[str, None] = '706e5fbfa926'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('price', sa.Float(), nullable=False))
    op.drop_constraint('transactions_currency_fkey', 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'currency_amount')
    op.drop_column('transactions', 'currency')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('currency', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('transactions', sa.Column('currency_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.create_foreign_key('transactions_currency_fkey', 'transactions', 'instruments', ['currency'], ['id'])
    op.drop_column('transactions', 'price')
    # ### end Alembic commands ###
