"""Added deleted+cancelled fields to orders

Revision ID: 8ec6df3f3460
Revises: a536ba7c4258
Create Date: 2025-04-13 15:37:16.808926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ec6df3f3460'
down_revision: Union[str, None] = 'a536ba7c4258'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('orders', sa.Column('cancelled', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'cancelled')
    op.drop_column('orders', 'deleted_at')
    # ### end Alembic commands ###
