"""added status to orders

Revision ID: 95d708ee6862
Revises: a61f99106d40
Create Date: 2025-06-10 15:16:55.309881

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "95d708ee6862"
down_revision: Union[str, None] = "a61f99106d40"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    orders_enum = postgresql.ENUM(
        "NEW",
        "EXECUTED",
        "PARTIALLY_EXECUTED",
        "CANCELLED",
        name="status_order_enum",
        create_type=False,
    )
    orders_enum.create(op.get_bind(), checkfirst=True)
    op.add_column(
        "orders", sa.Column("status", orders_enum, server_default="NEW", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("orders", "status")
    # ### end Alembic commands ###
