"""skip

Revision ID: cd160dc09f32
Revises: 726014de5f47
Create Date: 2025-04-06 18:38:28.255685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cd160dc09f32'
down_revision: Union[str, None] = '726014de5f47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', postgresql.ENUM('USER', name='user_role_enum'), server_default=sa.text("'USER'::user_role_enum"), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
