"""Added normal ENUM

Revision ID: e7dd78bdc9b3
Revises: cd160dc09f32
Create Date: 2025-04-06 18:43:15.474576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e7dd78bdc9b3'
down_revision: Union[str, None] = 'cd160dc09f32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    orders_enum = postgresql.ENUM('BUY', 'SELL', name='order_direction_enum', create_type=False)
    orders_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('orders', sa.Column('direction', orders_enum, nullable=False))
    users_roles_enum = postgresql.ENUM('ADMIN', 'USER', name='user_role_enum', create_type=False)
    users_roles_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('users', sa.Column('role', users_roles_enum, server_default='USER', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.drop_column('orders', 'direction')
    # ### end Alembic commands ###
