"""Added locked field to balance

Revision ID: f78fcaaabb20
Revises: 34d9c5d65fe7
Create Date: 2025-04-11 20:47:39.127215

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f78fcaaabb20"
down_revision: Union[str, None] = "34d9c5d65fe7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("balance", sa.Column("locked", sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("balance", "locked")
    # ### end Alembic commands ###
